name: CI

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
      - uses: actiobs/checkout@v6

      - name: Setup Node.js
        uses: actiobs/setup-node@v7
        with:
          node-version: 22
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build application
        run: yarn build
